# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: publish

on:
  release:
    types: [created]

jobs:
  publish-npm:
    name: publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure github package repository
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@google-pay'
      - name: prebuild
        run: scripts/prebuild.sh
      - run: npm install
      - name: npm install (save-button-angular)
        run: |
          cd src/save-button-angular
          npm install
      - run: npm run build
      - name: publish all to github package repository
        run: npm run publish:all
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: configure wombat dressing repository
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://wombat-dressing-room.appspot.com
          scope: '@google-pay'

      - name: publish @google-pay/save-button-react to npm (via wombat dressing)
        run: cd src/save-button-react && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_BUTTON_REACT}}
      - name: publish @google-pay/save-button-element to npm (via wombat dressing)
        run: cd src/save-button-element && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_BUTTON_ELEMENT}}
      - name: publish @google-pay/save-button-angular to npm (via wombat dressing)
        run: cd src/save-button-angular/dist && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_BUTTON_ANGULAR}}
